version: '3.8'

services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - 'mongo-data:/data/db'
      - './init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
    healthcheck:
      test:
        - CMD
        - mongo
        - '--eval'
        - "db.adminCommand('ping')"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8003:1337'
    environment:
      MINIO_ACCESS_KEY:  ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MONGODB_URI: 'mongodb://root:example@mongo:27017/cpm?authSource=admin'
    depends_on:
      - mongo
    restart: unless-stopped
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8004:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  mongo-data:
    name: mongo-data
